services:

  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888


  garden-kafka:
    container_name: kafka
    image: debezium/kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181


  apicurio:
    image: quay.io/apicurio/apicurio-registry-mem:2.4.2.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: "true"
      QUARKUS_HTTP_PORT: 8086

  rest-items:
    container_name: rest-items
    image: garden-app/rest-items:1.0
    depends_on:
      - apicurio
      - garden-kafka
    environment:
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092
    ports:
      - '7806:7806'
    restart: on-failure

  rest-planting-allocation:
    container_name: rest-planting-allocation-service
    image: garden-app/rest-plant-allocation:1.0
    depends_on:
      - apicurio
      - garden-kafka
    environment:
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092
    ports:
      - '7808:7808'
    restart: on-failure